config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :users
  resources :tasks
  resources :users, only: [:show]
  root 'tasks#index'

  put '/tasks/:id', to: 'tasks#update', as: 'update_task'

  resources :tasks do
    member do
      put 'change-status'
    end
  end

  match "/404", to: "errors#not_found", :via => :all
  match "/500", to: "errors#internal_server_error", :via => :all

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :child, class_name:'User', foreign_key: "child_id"
	belongs_to :mother, class_name:'User', foreign_key: "mother_id"

  	validates :title, presence: true
  	validates :mother, presence: true

  	has_attached_file :proof, styles: {
		medium: '300x300>',
		thumb: '100x100'
	}
	validates_attachment_content_type :proof, content_type: /\Aimage/
	validates_attachment_file_name :proof, matches: [/png\Z/, /jpe?g\Z/, /gif\Z/]
	validates_with AttachmentSizeValidator,
		attributes: :proof,
		less_than: 5.megabytes
	do_not_validate_attachment_file_type :proof
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :change_status]
  # before_action :authenticate_user!
  
  # GET /tasks
  # GET /tasks.json
  def index
    if current_user.role == "Mother"
      @tasks = Task.where(mother: current_user).all
    elsif current_user.role == "Child"
      @tasks = Task.where(child: current_user).all
    else
      @tasks = Task.all
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.mother = current_user
    @task.isDone = false
    
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        if @task.answer? or @task.proof.exists?
          @task.isDone = true
          @task.save
        end
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def change_status
    if @task.isDone == true
      @task.isDone = false
      @task.answer = nil
      @task.proof = nil
    else
      @task.isDone = true
    end
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task status was successfully updated' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :show }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :isDone, :mother_id, :child_id, :description, :answer, :proof)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="container">
  <div class="postit">
    <%= simple_form_for(@task) do |f| %>
      <% if @task.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

          <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-inputs">
        <%= f.input :title, required: true, autofocus: true %>
        <%= f.association :child, label: 'Child', class: 'form-control', required: true, collection: User.where(role: "child")  %><br>
        <%= f.input :description, as: :text, autofocus: true %>
      </div>
      <div class="form-actions">
        <div class="form-group">
          <%= f.submit class: 'button btn btn-default' %>
        </div>
      </div>
    <% end %>
    <div class="postit-buttons">
      <% if current_page?(edit_task_path(@task)) %>
        <p><%= link_to 'Show', @task %></p><!--
   --><% end %><!--
   --><p><%= link_to 'Back', tasks_path %></p>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
  <p id="notice"><%= notice %></p>

  <h1>Listing Tasks</h1>

  <div class="card-stack-container">
    <div id="cardStackContainer">
      <% @tasks.each do |task| %>
        <ul id="postit_<%= task.id %>" class="card-stack ui-sortable">
          <li class="stack-label"><%= task.title %></li>
          <li class="item"><%= task.created_at %></li>
          <li class="item"><%= task.mother.name %></li>
          <li class="item"><%= task.child.name %></li>
          <li class="item item-last">
            <table class="table">
              <tbody align=center>
                <td><%= link_to task, title:"Show" do %> <i class="fa fa-eye fa-2x" aria-hidden="true"></i> <% end %></td>
                <% if current_user == task.mother %>
                  <td><%= link_to edit_task_path(task), title:"Edit" do %> <i class="fa fa-pencil fa-2x" aria-hidden="true"></i> <% end %></td>
                  <td><%= link_to task, title:"Delete", method: :delete, data: { confirm: 'Are you sure?' } do %> <i class="fa fa-trash fa-2x" aria-hidden="true"></i> <% end %></td>
                <% end %>
              </tbody>
            </table>
          </li>
        </ul>
      <% end %>
      <% if current_user.role == 'Mother' %>
        <ul id="postit_new" class="card-stack ui-sortable">
          <li class="stack-label">New Task</li>
          <%= link_to new_task_path, title:"New" do %>
            <li class="item-new"><i class="fa fa-plus-square fa-4x" aria-hidden="true"></i></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="container rotate" align=center>
  <div class="postit">
    <% if @task.isDone == true %>
     <div class="sample"></div>
    <% end %>
    <p class="stack-label"> <b><%= @task.title %></b> </p>

    <% if notice %> 
      <p id="notice" class="alert alert-success"><%= notice %></p>
    <% end %>

    <p class="postit-description"><%= @task.description %></p>

    <table class="table"> 
      <tbody> 
        <tr> 
          <th scope="row">Created At</th> <td><%= @task.created_at %></td> 
        </tr>
        <tr> 
          <th scope="row">Mother</th> <td><%= @task.mother.name %></td> 
        </tr>
        <tr> 
          <th scope="row">Child</th> <td><%= @task.child.name %></td> 
        </tr>
        <tr> 
          <th scope="row">Is Done ?</th> <td><%= @task.isDone %></td> 
        </tr> 
      </tbody> 
    </table>

    <div class="postit-footer">
			<% if @task.isDone == true %>
        <p>
  				<%= link_to change_status_task_path(@task), method: :put, title: "Undone" do %>
            <i class="fa fa-times-circle-o fa-2x" aria-hidden="true"></i> Mark as undone
          <% end %>
        </p>
			<% else %>
        <p>
          <%= link_to change_status_task_path(@task), method: :put, title: "Done" do %>
            <i class="fa fa-check-circle-o fa-2x" aria-hidden="true"></i> Mark as done
          <% end %>
        </p><!--
     --><p>
          <a data-toggle="modal" data-target="#taskModal" title="Done with proof">
  				  <span class="fa-stack fa-2x fa-custom">
              <i class="fa fa-check-circle-o fa-stack-1x"></i>
              <strong class="fa-stack-1x check-text"><i class="fa fa-plus fa-custom-plus fa-1x" aria-hidden="true"></i></strong>
            </span> Mark as done with proof
          </a>
        </p>
			<% end %>
      <% if @task.answer? or @task.proof.exists? %>
        <div class="card-stack-container">
          <div id="cardStackContainer">
            <ul id="postit_answer" class="card-stack ui-sortable">
              <li class="stack-label">Answer</li>
              <li class="item"><%= @task.answer %></li>
            </ul>
            <ul id="postit_answer" class="card-stack ui-sortable" data-toggle="modal" data-target="#taskProofModal">
              <li class="stack-label">Proof</li>
              <li class="item"><%= image_tag @task.proof.url(:medium) %></li>
            </ul>
          </div>
        </div>
      <% end %>
      
      <div class="postit-buttons">
      <% if current_user.role == "Mother" %>
        <p><%= link_to 'Edit', edit_task_path(@task)%></p><!--
   --><% end %><!--
     --><p><%= link_to 'Back', tasks_path %></p>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="taskModal" tabindex="-1" role="dialog" aria-labelledby="taskModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times" aria-hidden="true"></i></button>
        <h3 class="modal-title" id="taskModalLabel">Add proof</h3>
      </div>
      <%= simple_form_for @task, url: update_task_path, method: :put do |f| %>
        <div class="modal-body">
          <%= f.input :answer, autofocus: true, label: "Written proof" %>
          <span>AND/OR</span><br/>
          <%= f.input :proof, as: :file, label: "Image proof" %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit 'Done', class: 'button btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="taskProofModal" tabindex="-1" role="dialog" aria-labelledby="taskProofModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times" aria-hidden="true"></i></button>
        <h3 class="modal-title" id="taskProofModalLabel">Proof</h3>
      </div>
      <div class="modal-body">
        <%= image_tag @task.proof.url %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= link_to "Download", @task.proof.url(:original, false), class: "button btn btn-primary" %>
      </div>
    </div>
  </div>
</div>